# Generated by Django 5.2.6 on 2025-09-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0017_chatconversation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatConversation',
        ),
    ]
