# Generated by Django 5.2.6 on 2025-09-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0019_chatbotuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotuser',
            name='preference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
