# Generated by Django 5.2.6 on 2025-09-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0020_chatbotuser_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotuser',
            name='preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
