# Generated by Django 5.2.6 on 2025-09-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0021_alter_chatbotuser_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='Inquiry Details'),
        ),
    ]
