# Generated by Django 5.2.6 on 2025-09-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0022_alter_inquiry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(default=1234, verbose_name='Inquiry Details'),
            preserve_default=False,
        ),
    ]
