# Generated by Django 4.2.6 on 2025-10-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edusetin_app', '0024_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='country',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
