# Generated by Django 6.0.5 on 2026-06-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_image',
        ),
        migrations.AddField(
            model_name='question',
            name='media_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='requires_option_a_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='requires_option_b_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='requires_option_c_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='requires_option_d_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='requires_option_e_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='requires_question_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, choices=[('PYQ', 'PYQ'), ('EDUSETIN', 'EDUSETIN'), ('OTHER', 'OTHER')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('QUESTION', 'Question'), ('OPTION_A', 'Option A'), ('OPTION_B', 'Option B'), ('OPTION_C', 'Option C'), ('OPTION_D', 'Option D'), ('OPTION_E', 'Option E')], max_length=20)),
                ('image', models.ImageField(upload_to='question_media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='student_management.question')),
            ],
            options={
                'ordering': ['media_type'],
                'unique_together': {('question', 'media_type')},
            },
        ),
    ]
