# Generated by Django 6.0.5 on 2026-06-05 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_remove_question_question_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='media_library/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='questionmedia',
            name='media_library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='student_management.medialibrary'),
        ),
        migrations.CreateModel(
            name='PendingMediaReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('QUESTION', 'Question'), ('OPTION_A', 'Option A'), ('OPTION_B', 'Option B'), ('OPTION_C', 'Option C'), ('OPTION_D', 'Option D'), ('OPTION_E', 'Option E')], max_length=20)),
                ('expected_media_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_media_refs', to='student_management.question')),
            ],
            options={
                'ordering': ['media_type'],
                'unique_together': {('question', 'media_type')},
            },
        ),
    ]
