# Generated by Django 6.0.5 on 2026-06-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0003_medialibrary_pendingmediaref_questionmedia_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmedia',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='question_media/'),
        ),
    ]
